(#75) Adicionando docstrings.
fga-eps-mds/2022-2-Squad08 pull request #78
Opened 2023-02-03 16:44 UTC by PedroSampaioDias

Co-Authored-By: BlimblimCFT <galefreitas@gmail.com>

## Descrição

Esse PR propõe a adição de docstrings para todas as funções, métodos e classes da aplicação. As docstrings fornecem informações claras e concisas sobre o que cada função faz, bem como seus argumentos e o tipo de valor retornado.

Todas as docstrings seguem  um padrão de estilo e passaram pelo Linter para garantir a sua qualidade.

Correções (#75)

## Tipo de alteração
Marque com um 'x' as alterações relevantes.

Exclua as opções que não são relevantes.

- [ ] Correção de bug (mudança ininterrupta que corrige um problema)
- [ ] Novo recurso (mudança ininterrupta que adiciona funcionalidade)
- [x] Mudança de última hora
- [ ] Esta alteração requer uma atualização da documentação

## Lista de controle:

- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Realizei uma auto-revisão do meu próprio código
- [ ] Eu comentei meu código, principalmente em áreas difíceis de entender
- [ ] Fiz as alterações correspondentes na documentação
- [ ] Minhas alterações não geram novos avisos
- [x] Verifiquei meu código e corrigi qualquer erro de ortografia

2023-02-03 16:49 UTC, PedroSampaioDias commented
@BlimblimCFT o teste do codeclimate falhou, todos os erros são de `line too long`, precisamos resolver

2023-02-04 00:58 UTC, BlimblimCFT commented
@Victor-oss corrigido erro de line too long do codeclimate

2023-02-04 01:05 UTC, daniel-de-sousa approved these changes
Código completo para colocar na main

2023-02-06 11:27 UTC, Leanddro13 approved these changes
Código revisado e testado

2023-02-06 12:02 UTC, daniel-de-sousa requested changes
Na main foram feitas algumas mudanças que precisam ser adicionadas e verificadas se não vai gerar nenhum comflito

2023-02-06 13:12 UTC, PedroSampaioDias commented
@daniel-de-sousa Poderia ser mais especifico no que deveríamos verificar?

2023-02-06 13:15 UTC, merged

2023-02-06 13:16 UTC, daniel-de-sousa commented
@PedroSampaioDias Essa branch está dois commits atrás da main, umas das mudanças ocorreu no arquivo automatização, o que provavélmente não causara problema.
O principal seria veeririficar se o conteúdo da issue 71 causaria algum conflito.